name: picturetalk-frontend # You can also change this to another name to avoid warning with existing group. 
services:
  frontend:
    container_name: pt-frontend
    build:
      context: ..
      dockerfile: src/Dockerfile
    ports:
      - ${NGINX_PORT}:5173
    networks:
      - picturetalk_pt-net
    environment:
      - NGINX_PROXY=${NGINX_PROXY}
      - NGINX_PORT=${NGINX_PORT}
networks:
  picturetalk_pt-net: # Check by using `docker network ls` command
    external: true
